### ISSUE TITLE
Can I import local pictures for management?

### ISSUE THREAD

**Issue by Sizukaze** [gazerdev/gazer#3]
Can directly import pictures for management? Or set up a folder to place pictures for management

**Comment by gazerdev** [comment]
Currently there's no built in support for importing new pictures for management. Local booru serves files out of the 'gazer/static/dump' subdirectory and gets tags and metadata from an sqlite database (postdata.db) with data automatically scraped from booru sites. If you wanted to import a local collection you would have to 

1) create entries for each image in the database 
2) move or copy the image into the dump folder structure which looks like this "dump/aa/2b/aa2bxxxxxxx.jpeg"

If you want to do this and have some existing tag data, your best bet would probably be writing an import script. Database schema is layed out in sqlalchemy models in models.py which can be used directly if you like. I'm working on adding an import script for some types of untagged images.
